sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - yarn run validate
after_success:
  - npm run report-coverage
  - npm run semantic-release
env:
  global:
    - secure: waK7c/moDG0HAhijQ85Da1u+S/TRTcKLAMWwAHYhY7caCOZLabHEMTygvfocK4la2kvZMFbILBRRFc2+PToN0NQKd/8t8TXKyZKFxhb85haMA7R1e3gpB4zeCn6cMNIIS0ZKdlOcHW6eUbdC9udZDLEZZRn9GT9Werg5abF3OxJT81VNdBU8IbSIfofDbobWM/0QC6gr41a3MwPPVBw1oHRXfxuJEM8DORRKw2JIye2nPVkPdkW+jRNmOjiv8R9fhIS/fKMjWJn0Uuw6a8l3ffZ9YB2hcxKWW1qaqrRzEytXclJdeRetk5zpnY0eitoN2a4FfufUQmBKfAuh6tGVsYxp4GLHrdFXW2q81/OfJSVPO3NVEv0fsTWOV22bPW3GunTzmqi3ny24UUnjFC40QPZCx+lq0vvwFoxSoj8tJ3N7Rsd8eRfhNftggYkjeY9ZVBBWjbkL9JoONpLuz2NfKbQo7PZZOUTqq7cArnwJ//yRHtI+PuAiKF+EGMhxJMMHnobLAmFjpQMQlf8NXAnI6PKnotI/GEGUs37wGUNne/2+x3XLMzeHxmz+NnoC8UGBlSIOcpC8Jl8sCvb4OyS/n6V5ky+trgvIpcjKpUWLPfVG0Q9y98PAR4H0Y7X6AHTC5CkPFT4TpV79ydiEoNZ6E80bLIbV4qRUVgEA1PtD2Rw=
    - secure: WybrvGpPFRjfDUDFaGUbT6lL3n/1YkMyLOJABqhFDlRSsaYhG3xKhcm1yfkVLSzhhasC8u5wjbStyv8ubrWLWMV0vyW+Djsjp7U+tRA1uPWfEOTpwCZ/Rn4hZmbWGntHru1Clq2JBCgw7ihv9XCw6wo9fzdNFV0uP5JKKaB6RsdOyaBjr4ePE/jGr94Q17NX76YSJ8FNbiqj1qawpLFcBDv8/DFn1r3yCdesGs/TcX2ahnCdnOL/ODyuBkgyh0KUxwKlPMG0l99t/+tDUBcBAG30EDFh4KAobZ3j4BJRB6PmxcENEoYmHYsNf4NZkbhresSpg3UGws2F3SZs3sBfghKeOA5QkaasWwpjtoV5SIlRW3u69CINH9k3WpkKN0k4vaMngfoeRhIVkCqWEul3n9Jk9be07WIyJc9MA8ccZpnSiBD4hBd2VtzfCdD8w603gztBVUCnK4eoFT4AbK0LjTfJdND4o5w1LFdyFcMtDQASe32QfVIPk3+yqU2gc/PNxoNjp1Sj+T6fgnuTHBmaWb0EqE/rN2rIyUIgbJqFKpk+4ZNTQ+Rqg7iAZQ/SzX6xsSCwl1IEeEonLbv54snCAXzojBBrTpOfyrPJ3eSyind5ZsBeQrmWjTKYTAddAA/MKYk7nAMU+SPB75X3SUjSY7kvCFJpt6Hz2ynqQahiJg8=
