sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - yarn run validate
after_success:
  - npm run report-coverage
  - npm run semantic-release
